### ISSUE TITLE
Assignment Progress

### ISSUE THREAD

**Issue by dluman** [term-world/traffic-circle-solution#25]
# `TODO`s

Based on the GatorGrader report for this run, here's a summary of what you've got left to do.

## Reflection

- [ ] No TODO markers left in reflection.md
- [ ] reflection.md checkboxes checked attested to

## Let there be Light (North)

- [x] No TODO markers left in north&#x2F;Stoplight.py
- [x] north&#x2F;Stoplight.py contains at least two if statements for the light variable

## Let there be Light (North-East)

- [x] No TODO markers left in north-east&#x2F;Stoplight.py
- [x] north-east&#x2F;Stoplight.py contains the light variable in conditional statements
- [ ] north-east&#x2F;Stoplight.py contains the people_waiting variable in conditional statements

## Let there be Light (North-West)

- [x] No TODO markers left in north-west&#x2F;Stoplight.py
- [x] north-west&#x2F;Stoplight.py contains the light variable in conditional statements
- [x] north-west&#x2F;Stoplight.py sets the crosswalk variable

## Let there be Light (South)

- [x] No TODO markers left in south&#x2F;Stoplight.py
- [x] south&#x2F;Stoplight.py contains at least two if statements for the light variable

## Let there be Light (South-West)

- [x] No TODO markers left in south-west&#x2F;Stoplight.py
- [ ] south-west&#x2F;Stoplight.py contains at least two if statements for the crosswalk variable

## Let there be Light (East)

- [x] No TODO markers left in east&#x2F;Stoplight.py
- [x] east&#x2F;Stoplight.py contains at least two if statements for the light variable
- [x] east&#x2F;Stoplight.py accounts for the turn signal
- [x] east&#x2F;Stoplight.py accounts for the hold between signals

## Let there be Light (West)

- [x] No TODO markers left in west&#x2F;Stoplight.py
- [x] west&#x2F;Stoplight.py accounts for the timeout between signals
- [x] west&#x2F;Stoplight.py contains at least two if statements for the light variable

## The Public Transport Project (Bus)

- [x] No TODO markers left in Bus.py (wherever it ended up)
- [ ] Bus has traveled (is no longer in main folder)

## The Private Transport Project (Car)

- [x] No TODO markers left in Car.py (wherever it ended up)
- [ ] Car has traveled (is no longer in main folder)

## Let there be Light (South-East)

- [x] north-east&#x2F;Stoplight.py sets the crosswalk variable
- [x] north-east&#x2F;Stoplight.py uses the countdown variable in conditional statements
- [x] north-east&#x2F;Stoplight.py uses the light variable in conditional statements

## The Public Transport Project

- [x] Bus.py (wherever it is) uses a while statement

## The Private Transport Project

- [ ] Car.py (where&#39;d it go?) uses at least two if statements for the signal variable

## Percent complete

Based on the checks achieved, this assignment is `76%` complete.
